Atomize RenameFile in KeyManagedEncryptedEnv
tikv/rocksdb pull request #222
Opened 2020-12-16 08:55 UTC by hunterlxt

related issue: https://github.com/tikv/tikv/issues/9115

Summary: we need to update encryption metadata via `encryption::DataKeyManager`, which cannot combine with the actual file operation into one atomic operation. In `RenameFile`, when the src_file has been removed, power is off, then we may lost the file info of src_file next restart.

Signed-off-by: Xintao <hunterlxt@live.com>

2020-12-16 08:56 UTC, hunterlxt commented
@tabokie @Connor1996  PTAL

2020-12-16 09:57 UTC, tabokie approved these changes
Looks good, but I want to make sure future implementation won't embed critical logic inside `Rename` method, e.g. file-specific state transfer. Maybe add a comment or simply deprecate the function in `KeyManager`?

2020-12-16 12:08 UTC, hicqu approved these changes

2020-12-16 23:14 UTC, yiwu-arbug requested changes

2020-12-16 23:14 UTC, yiwu-arbug commented on encryption/encryption.cc
> +    key_manager_->DeleteFile(src_fname);
```suggestion
    s = key_manager_->DeleteFile(src_fname);
```

2020-12-16 23:16 UTC, yiwu-arbug commented
> Looks good, but I want to make sure future implementation won't embed critical logic inside `Rename` method, e.g. file-specific state transfer. Maybe add a comment or simply deprecate the function in `KeyManager`?

Great suggestion. Let's remove `KeyManager::RenameFile` in encryption.h.

2020-12-16 23:16 UTC, yiwu-arbug commented
We need similar changes for TiKV logic as well.

2020-12-17 07:07 UTC, yiwu-arbug commented
revert redundant formatter change?

2020-12-17 07:08 UTC, yiwu-arbug commented on encryption/encryption.cc
> +        key_manager_->DeleteFile(dst_name);
`assert(delete_status.ok())`

2020-12-17 22:57 UTC, yiwu-arbug commented on encryption/encryption.cc
> +    assert(delete_status.ok())
```suggestion
    assert(delete_status.ok());
```

2020-12-17 22:57 UTC, yiwu-arbug commented on encryption/encryption.cc
> +    assert(delete_status.ok())
```suggestion
    assert(delete_status.ok());
```

2020-12-18 06:30 UTC, yiwu-arbug approved these changes
LGTM

2020-12-18 07:16 UTC, merged